# Generated by Django 2.0.7 on 2018-07-30 09:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_contact', models.TextField(blank=True, null=True)),
                ('address_phone', models.TextField(blank=True, null=True)),
                ('address_area', models.TextField(blank=True, null=True)),
                ('address_detail', models.TextField(blank=True, null=True)),
                ('address_mail', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem_GroupProduct',
            fields=[
                ('cartItem_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pro_count', models.IntegerField()),
                ('pro_price', models.IntegerField()),
                ('is_checked', models.BooleanField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CartItem_ShopProduct',
            fields=[
                ('cartItem_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pro_count', models.IntegerField()),
                ('pro_price', models.IntegerField()),
                ('is_checked', models.BooleanField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupNorm',
            fields=[
                ('norm_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('norm_name', models.TextField()),
                ('norm_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupProduct',
            fields=[
                ('pro_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pro_name', models.TextField()),
                ('pro_price', models.IntegerField()),
                ('pro_origin_price', models.IntegerField()),
                ('pro_remain', models.IntegerField()),
                ('pro_desc', models.TextField()),
                ('pro_spec', models.TextField()),
                ('pro_weight', models.TextField()),
                ('pro_package', models.TextField()),
                ('pro_life', models.TextField()),
                ('pro_store_method', models.TextField()),
                ('on_shelf', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupProductPicture',
            fields=[
                ('pic_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('group_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.GroupProduct')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_num', models.IntegerField()),
                ('order_status', models.IntegerField()),
                ('order_offer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_totalprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('send_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('order_comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem_GroupProduct',
            fields=[
                ('orderitem_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_time', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.GroupProduct')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem_ShopProduct',
            fields=[
                ('orderitem_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_time', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('groupuser_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_code', models.TextField()),
                ('group_number', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('group_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('type_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_name', models.TextField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='shop.ProductType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RedPack',
            fields=[
                ('red_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('red_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_used', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop_name', models.TextField()),
                ('shop_area', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopBannar',
            fields=[
                ('bannar_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bannar_url', models.TextField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('cart_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('pro_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pro_name', models.TextField()),
                ('pro_price', models.IntegerField()),
                ('pro_origin_price', models.IntegerField(blank=True, null=True)),
                ('pro_remain', models.IntegerField()),
                ('pro_desc', models.TextField(blank=True, null=True)),
                ('pro_spec', models.TextField(blank=True, null=True)),
                ('pro_weight', models.TextField(blank=True, null=True)),
                ('pro_package', models.TextField(blank=True, null=True)),
                ('pro_life', models.TextField(blank=True, null=True)),
                ('pro_store_method', models.TextField(blank=True, null=True)),
                ('on_shelf', models.BooleanField()),
                ('can_group', models.NullBooleanField()),
                ('pro_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ProductType')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShopProductPicture',
            fields=[
                ('pic_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('shop_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ShopProduct')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
                ('user_image', models.TextField()),
                ('user_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Address')),
            ],
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.User'),
        ),
        migrations.AddField(
            model_name='redpack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.User'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='group_monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.User'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='group_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.GroupProduct'),
        ),
        migrations.AddField(
            model_name='orderitem_shopproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ShopProduct'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_redpack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.RedPack'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.User'),
        ),
        migrations.AddField(
            model_name='groupproduct',
            name='pro_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ProductType'),
        ),
        migrations.AddField(
            model_name='groupproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop'),
        ),
        migrations.AddField(
            model_name='cartitem_shopproduct',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ShoppingCart'),
        ),
        migrations.AddField(
            model_name='cartitem_shopproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ShopProduct'),
        ),
        migrations.AddField(
            model_name='cartitem_groupproduct',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ShoppingCart'),
        ),
        migrations.AddField(
            model_name='cartitem_groupproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.GroupProduct'),
        ),
    ]
