# Generated by Django 2.0.7 on 2018-08-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupproduct',
            name='pro_origin_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='groupproduct',
            name='pro_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='pro_origin_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='pro_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
