# Generated by Django 2.0.7 on 2018-08-04 07:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180803_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('dis_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('minus', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='CartItem_ShopProduct',
            new_name='CartItem',
        ),
        migrations.RenameModel(
            old_name='OrderItem_ShopProduct',
            new_name='OrderItem',
        ),
        migrations.RenameModel(
            old_name='ShopProductPicture',
            new_name='ProductPicture',
        ),
        migrations.RemoveField(
            model_name='cartitem_groupproduct',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem_groupproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='groupproductpicture',
            name='group_product',
        ),
        migrations.RemoveField(
            model_name='orderitem_groupproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem_groupproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='groupproduct',
            name='on_shelf',
        ),
        migrations.RemoveField(
            model_name='groupproduct',
            name='pro_desc',
        ),
        migrations.RemoveField(
            model_name='groupproduct',
            name='pro_life',
        ),
        migrations.RemoveField(
            model_name='groupproduct',
            name='pro_name',
        ),
        migrations.RemoveField(
            model_name='groupproduct',
            name='pro_origin_price',
        ),
        migrations.RemoveField(
            model_name='groupproduct',
            name='pro_package',
        ),
        migrations.RemoveField(
            model_name='groupproduct',
            name='pro_price',
        ),
        migrations.RemoveField(
            model_name='groupproduct',
            name='pro_remain',
        ),
        migrations.RemoveField(
            model_name='groupproduct',
            name='pro_spec',
        ),
        migrations.RemoveField(
            model_name='groupproduct',
            name='pro_store_method',
        ),
        migrations.RemoveField(
            model_name='groupproduct',
            name='pro_type',
        ),
        migrations.RemoveField(
            model_name='groupproduct',
            name='pro_weight',
        ),
        migrations.RemoveField(
            model_name='groupproduct',
            name='shop',
        ),
        migrations.AddField(
            model_name='groupproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.ShopProduct'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='activityType',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='group_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ShopProduct'),
        ),
        migrations.DeleteModel(
            name='CartItem_GroupProduct',
        ),
        migrations.DeleteModel(
            name='GroupProductPicture',
        ),
        migrations.DeleteModel(
            name='OrderItem_GroupProduct',
        ),
        migrations.AddField(
            model_name='discount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ShopProduct'),
        ),
    ]
