# Generated by Django 2.0.7 on 2018-08-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180804_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='comment',
            field=models.TextField(default='满50减20'),
        ),
        migrations.AddField(
            model_name='groupproduct',
            name='comment',
            field=models.TextField(default='可拼团'),
        ),
    ]
