# Generated by Django 2.0.7 on 2018-08-09 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180804_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 9, 15, 11, 53, 114250)),
        ),
        migrations.AddField(
            model_name='user',
            name='user_openid',
            field=models.TextField(default='unknown user'),
        ),
    ]
