# Generated by Django 2.0.7 on 2018-08-09 07:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180809_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_address',
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 9, 15, 23, 29, 490888)),
        ),
    ]
