# Generated by Django 2.0.7 on 2018-08-09 15:07

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180809_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='limitTimeSale',
            fields=[
                ('limit_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('remain', models.IntegerField()),
                ('comment', models.TextField(default='限时出售')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 9, 23, 7, 51, 196722)),
        ),
    ]
