# Generated by Django 2.0.7 on 2018-08-09 15:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180809_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='limittimesale',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.ShopProduct'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 9, 23, 18, 26, 284895)),
        ),
    ]
