# Generated by Django 2.0.7 on 2018-08-10 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20180809_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='fullCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='fullMinus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='remain',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 10, 11, 0, 56, 776608)),
        ),
    ]
