# Generated by Django 2.0.7 on 2018-08-11 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20180810_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='group_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 11, 21, 47, 37, 634096)),
        ),
    ]
