# Generated by Django 2.0.7 on 2018-08-13 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20180811_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='type_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 13, 9, 15, 25, 129841)),
        ),
    ]
