# Generated by Django 2.0.7 on 2018-08-13 02:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20180813_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_offer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_redpack',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_offer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_redpack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.RedPack'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 13, 10, 51, 42, 354724)),
        ),
    ]
