# Generated by Django 2.0.7 on 2018-08-13 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20180813_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 13, 11, 4, 20, 323097)),
        ),
    ]
