# Generated by Django 2.0.7 on 2018-08-13 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20180813_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='group_maxNum',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 13, 13, 27, 35, 837220)),
        ),
    ]
