# Generated by Django 2.0.7 on 2018-08-14 03:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20180813_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='product',
        ),
        migrations.DeleteModel(
            name='GroupNorm',
        ),
        migrations.RemoveField(
            model_name='groupproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='limittimesale',
            name='product',
        ),
        migrations.RenameField(
            model_name='shopproduct',
            old_name='group_price',
            new_name='groupPrice',
        ),
        migrations.RenameField(
            model_name='shopproduct',
            old_name='count',
            new_name='limitCount',
        ),
        migrations.RenameField(
            model_name='shopproduct',
            old_name='remain',
            new_name='limitRemain',
        ),
        migrations.RenameField(
            model_name='shopproduct',
            old_name='pro_life',
            new_name='pro_detail',
        ),
        migrations.RenameField(
            model_name='shopproduct',
            old_name='pro_package',
            new_name='pro_img',
        ),
        migrations.RenameField(
            model_name='shopproduct',
            old_name='pro_spec',
            new_name='pro_norm',
        ),
        migrations.RenameField(
            model_name='shopproduct',
            old_name='pro_store_method',
            new_name='pro_producer',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_redpack',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='can_group',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='pro_weight',
        ),
        migrations.AddField(
            model_name='order',
            name='order_redpack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.RedPack'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productpicture',
            name='pictureType',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='limitPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='limitTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 14, 11, 33, 36, 130753)),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 14, 11, 33, 36, 127755)),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='GroupProduct',
        ),
        migrations.DeleteModel(
            name='limitTimeSale',
        ),
    ]
