# Generated by Django 2.0.7 on 2018-08-14 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20180814_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_useRedPack',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='limitTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 14, 17, 23, 3, 288374)),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 14, 17, 23, 3, 284356)),
        ),
    ]
