# Generated by Django 2.0.7 on 2018-08-15 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20180815_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='limitTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 7, 1, 0, 400928), verbose_name='限时商品截止时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 16, 7, 1, 0, 396931), verbose_name='创建时间'),
        ),
    ]
