# Generated by Django 2.0.7 on 2018-08-15 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20180816_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='type_icon',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d', verbose_name='分类图标'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='limitTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 7, 1, 29, 54543), verbose_name='限时商品截止时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 16, 7, 1, 29, 49545), verbose_name='创建时间'),
        ),
    ]
