# Generated by Django 2.0.7 on 2018-08-16 01:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20180816_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('spec_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spec_name', models.TextField()),
                ('spec_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='limitTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 9, 15, 55, 980112), verbose_name='限时商品截止时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 16, 9, 15, 55, 977124), verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='productspec',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ShopProduct'),
        ),
    ]
