# Generated by Django 2.0.7 on 2018-08-16 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20180816_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='limitTime',
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='limitEndTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='限时商品截止时间'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='limitStartTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='限时商品开始时间'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='reachTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预售商品到达时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.TextField(default='2018081616242098', verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 16, 16, 24, 20, 16989), verbose_name='创建时间'),
        ),
    ]
