# Generated by Django 2.0.7 on 2018-08-16 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20180816_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_address',
            field=models.TextField(blank=True, null=True, verbose_name='商店地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.TextField(default='2018081616343535', verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 16, 16, 34, 35, 579521), verbose_name='创建时间'),
        ),
    ]
