# Generated by Django 2.0.7 on 2018-08-17 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20180816_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_city',
            field=models.TextField(blank=True, null=True, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='address',
            name='address_province',
            field=models.TextField(blank=True, null=True, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.TextField(default='2018081713420829', verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 17, 13, 42, 8, 75199), verbose_name='创建时间'),
        ),
    ]
