# Generated by Django 2.0.7 on 2018-08-20 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20180820_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='redpack',
            name='red_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='到期时间'),
        ),
        migrations.AddField(
            model_name='redpack',
            name='red_name',
            field=models.TextField(default='放心优选全场红包', verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='redpack',
            name='red_overdue',
            field=models.BooleanField(default=False, verbose_name='是否过期'),
        ),
        migrations.AddField(
            model_name='redpack',
            name='red_satisfy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='门槛数额'),
        ),
        migrations.AddField(
            model_name='redpack',
            name='red_type',
            field=models.IntegerField(default=0, verbose_name='红包类型'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.TextField(default='2018082011154766', verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 20, 11, 15, 47, 29313), verbose_name='创建时间'),
        ),
    ]
