# Generated by Django 2.0.7 on 2018-08-20 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_auto_20180820_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='searchTimes',
            field=models.IntegerField(default=0, verbose_name='搜索次数'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.TextField(default='2018082017493861', verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 20, 17, 49, 38, 183465), verbose_name='创建时间'),
        ),
    ]
