# Generated by Django 2.0.7 on 2018-08-21 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_auto_20180820_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='shop',
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='shops',
            field=models.ManyToManyField(to='shop.Shop'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.TextField(default='2018082116242168', verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 21, 16, 24, 21, 547789), verbose_name='创建时间'),
        ),
    ]
