# Generated by Django 2.0.7 on 2018-08-24 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_auto_20180821_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopbannar',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.TextField(default='2018082410142195', verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 24, 10, 14, 21, 533261), verbose_name='创建时间'),
        ),
    ]
