# Generated by Django 2.0.7 on 2018-08-24 02:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_auto_20180824_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopbannar',
            name='banner_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.ProductType'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.TextField(default='2018082410215066', verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='shopbannar',
            name='position',
            field=models.IntegerField(blank=True, null=True, verbose_name='布局位置'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 24, 10, 21, 50, 866302), verbose_name='创建时间'),
        ),
    ]
